-- Function for saving record to database
CREATE OR REPLACE FUNCTION saveOrder(text, text, text, text) RETURNS void AS '
  INSERT INTO public."Orders" ("pizzaSizeID", "pizzaFlavourID", "pizzaToppingID", "deliveryAddress") VALUES ((SELECT id FROM "PizzaSizes" WHERE name LIKE $1 LIMIT 1), (SELECT id FROM "PizzaFlavours" WHERE name LIKE $2 LIMIT 1), (SELECT id FROM "PizzaToppings" WHERE name LIKE $3 LIMIT 1), $4);
' LANGUAGE SQL

-- SQL for Orders tables
create table public."Orders" (
    id bigint generated by default as identity,
    "pizzaFlavourID" bigint not null,
    "pizzaToppingID" bigint null,
    "pizzaSizeID" bigint null,
    "deliveryAddress" text null,
    time timestamp without time zone null default now(),
    constraint Orders_pkey primary key (id),
    constraint Orders_pizzaFlavourID_fkey foreign key ("pizzaFlavourID") references "PizzaFlavours" (id) on update cascade on delete cascade,
    constraint Orders_pizzaSizeID_fkey foreign key ("pizzaSizeID") references "PizzaSizes" (id) on update cascade on delete cascade,
    constraint Orders_pizzaToppingID_fkey foreign key ("pizzaToppingID") references "PizzaToppings" (id) on update cascade on delete cascade
  ) tablespace pg_default;

-- SQL for PizzaFlavours tables
create table public."PizzaFlavours" (
    id bigint generated by default as identity,
    name text not null,
    constraint PizzaFlavours_pkey primary key (id)
  ) tablespace pg_default;

-- SQL for PizzaSizes tables
create table public."PizzaSizes" (
    id bigint generated by default as identity,
    name text not null,
    constraint PizzaSizes_pkey primary key (id)
  ) tablespace pg_default;

-- SQL for PizzaToppings tables
create table public."PizzaToppings" (
    id bigint generated by default as identity,
    name text not null,
    constraint PizzaToppings_pkey primary key (id)
  ) tablespace pg_default;